// Import modules
import TheComponent from "./models/Component.js";
import TheService from "./models/Service.js";
import Examinable from "./models/Examinable.js";
import InputBind from "./models/InputBind.js";
// Import functions from utils.js
import {
    capitalize,
    flatten,
    formatDate,
    formatCurrency,
    roundDecimals,
    isEmpty,
    mergeObjects
} from "./utils/utils.js";

// Import functions from sneaker.js
import {
    initialRender,
    initHtml,
    initRender,
    render,
    initCss,
    DOMLoaded,
    bindButton,
    setInput,
    enableRoutes,
    emit,
    receive,
    populateTable,
    uuid,
    asLocalStorage,
    renderEach,
    bindInputs,
    values,
    validate,
    applyStyles,
    write,
    read,
    navigate,
    getNavigateState,
    pagMax,
    pagMin,
    paginatorBack,
    paginatorNext,
    initializePaginator,
    multiRender,
    multiRenderClick,
    multiRenderWriteImageSrc,
    multiRenderWriteText,
    writeImgSrc
} from "./sneaker.js";

// Export functions and modules
export {
    TheComponent,
    TheService,
    InputBind,
    Examinable,
    pagMax,
    pagMin,
    paginatorBack,
    paginatorNext,
    initializePaginator,
    write,
    read,
    initialRender,
    initHtml,
    initRender,
    render,
    initCss,
    DOMLoaded,
    bindButton,
    setInput,
    enableRoutes,
    emit,
    receive,
    populateTable,
    uuid,
    asLocalStorage,
    renderEach,
    bindInputs,
    values,
    validate,
    applyStyles,
    capitalize,
    flatten,
    formatCurrency, 
    formatDate,
    roundDecimals,
    isEmpty,
    mergeObjects,
    navigate,
    getNavigateState,
    multiRender,
    multiRenderClick,
    multiRenderWriteImageSrc,
    multiRenderWriteText,
    writeImgSrc
};
